### ISSUE TITLE
Is it works with Expo ?

### ISSUE THREAD

**Issue by NgKhanh** [jgrancher/react-native-sketch#35]
Same code with your basic example but it doesn't work. I'm using Expo now

**Comment by jgrancher** [comment]
I've been interested in Expo for a while... But from what I know (and please correct me if i'm wrong), there's no way to make this library work without [detaching Expo](https://docs.expo.io/versions/latest/guides/detach.html). The reason is, it uses native Objective-C code and not only just Javascript to make it work, so unfortunately, it can't be supported.

**Comment by jgrancher** [comment]
Closing as there's not much I can do here, at least for now.
